[workspace]
authors = ["Szil√°gyi Csaba <csabi32105@gmail.com>"]
channels = ["conda-forge"]
name = "cv-filter"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
django = ">=5.2.8,<6"
psycopg2-binary = ">=2.9,<3"

[pypi-dependencies]
djangorestframework = ">=3.15,<4"
djangorestframework-simplejwt = ">=5.4,<6"
